CREATE OR REPLACE DATABASE healthdata_db;

USE HEALTHDATA_DB;

CREATE OR REPLACE SCHEMA healthdata_schema;

CREATE OR REPLACE TABLE HEALTHDATA_TABLE(
    Timestamp TIMESTAMP_NTZ NOT NULL,
    Step_Count INTEGER,
    Heartbeat INTEGER,
    Glucose_Rate FLOAT,
    Blood_Pressure_Systolic INTEGER,
    Blood_Pressure_Diastolic INTEGER,
    SpO2 FLOAT,
    Body_Temperature FLOAT,
    Calories_Burned FLOAT,
    Hydration_Level FLOAT,
    Sleep_Quality FLOAT
);

SELECT * FROM HEALTHDATA_TABLE;

CREATE OR REPLACE FILE FORMAT json_format
    type = 'json';


LIST @HEALTHDATA_STAGE;


COPY INTO healthdata_TABLE
FROM @HEALTHDATA_STAGE
FILE_FORMAT = (TYPE = 'JSON')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

SELECT * FROM HEALTHDATA_TABLE;

REMOVE @HEALTHDATA_STAGE;

CREATE OR REPLACE PIPE healthdata_pipe
AUTO_INGEST = TRUE
AS COPY INTO healthdata_table
FROM @HEALTHDATA_STAGE
FILE_FORMAT = (TYPE = 'JSON')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'CONTINUE';

SHOW PIPES;


SELECT * FROM healthdata_table;

TRUNCATE TABLE HEALTHDATA_TABLE;